collections:
  # Install a collection from Ansible Galaxy.
  - name: ansible.posix
    version: ">=1.6.0"
    source: https://galaxy.ansible.com
  - name: community.general
    version: ">=10.3.0"
    source: https://galaxy.ansible.com
