collections:
  # Install a collection from Ansible Galaxy.
  - name: ansible.posix
    version: ">=1.6.0"
    source: https://galaxy.ansible.com
  - name: community.general
    version: ">=10.3.0"
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    version: ">=5.1.0"
    source: https://galaxy.ansible.com
  - name: community.kubernetes
    version: ">=1.2.1"
    source: https://galaxy.ansible.com
  - name: cloud.common
    version: ">=4.0.0"
    source: https://galaxy.ansible.com
  - name: community.docker
    version: ">=4.0.0"
    source: https://galaxy.ansible.com
