apiVersion: v1
kind: Pod
metadata:
  name: app-v2
  namespace: default
  labels:
    app: app-v2
spec:
  containers:
    - name: app-v2
      image: docker.io/library/app_v2:latest
      ports:
        - containerPort: 7002
      resources:
        requests:
          memory: "128Mi"
          cpu: "150m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: app-v2-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: app-v2
  ports:
    - port: 80
      targetPort: 7002
      protocol: TCP
