apiVersion: v1
kind: Pod
metadata:
  name: app-v1
  namespace: default
  labels:
    app: app-v1
spec:
  containers:
    - name: app-v1
      image: docker.io/library/app_v1:latest
      ports:
        - containerPort: 7001
      resources:
        requests:
          memory: "128Mi"
          cpu: "150m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: app-v1-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: app-v1
  ports:
    - port: 80
      targetPort: 7001
      protocol: TCP
