apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: default
  labels:
    app: webserver
spec:
  containers:
    - name: webserver
      image: docker.io/library/webserver:latest
      ports:
        - containerPort: 443
      resources:
        requests:
          memory: "128Mi"
          cpu: "150m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservice
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: ttt.skfs2m.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webserver-service
                port:
                  number: 443
